### ISSUE TITLE
Handling of unary escape operator.

### ISSUE THREAD

**Issue by UnquietCode** [SomMeri/less4j#184]
First of all, thanks for the most excellent library! Per the goal of striving for 100% compatibility, here is a report of an incompatibility that I have encountered.

This is valid for less.js:

``` css
.transition(@transition) {
  -webkit-transition: @transition;
     -moz-transition: @transition;
       -o-transition: @transition;
          transition: @transition;
}

@hover-speed: .1s;

.btn {
    text-decoration: none;
    .transition(background-color @hover-speed linear~',' color @hover-speed linear);
}
```

However this line is invalid in less4j:

``` css
.transition(background-color @hover-speed linear~',' color @hover-speed linear);
```

I'm not sure who is correct in this matter, but separating the unary `~` operator from the preceding property value, changing it to the following, creates valid CSS in both less.js and less4j:

``` css
.transition(background-color @hover-speed linear ~',' color @hover-speed linear);
```
