### ISSUE TITLE
Wrong order of imported files for @import (once)

### ISSUE THREAD

**Issue by Doccrazy** [SomMeri/less4j#213]
Traversal order for import (once) statements should be depth first, not breadth first. 

The test compile-basic-features\import\import-once-order.less compiles differently with less.js than with less4j. The output of _lessc import-once-order.less_ is:

``` css
chained-import-1 {
  content: chained-import-1;
}
chained-import-2 {
  content: chained-import-2;
}
h1 {
  color: green;
}
```

(tested with less.js 1.7.0)
