### ISSUE TITLE
Charset and variable declaration at file beginning lead to exception

### ISSUE THREAD

**Issue by r-zander** [SomMeri/less4j#237]
Hi there,

just started with Less4j today (via [Wicket-Bootstrap-Less](https://github.com/l0rdn1kk0n/wicket-bootstrap)), so chances are good that my issue isn't really one - but at least Less.js behaved different than less4j and I wasn't able to find this behavior documented.

Wicket bootstrap less uses less4j like this:

``` Java
ThreadUnsafeLessCompiler compiler = new ThreadUnsafeLessCompiler();
LessCompiler.Configuration configuration = new LessCompiler.Configuration();
configuration.getSourceMapConfiguration().setLinkSourceMap(false);
LessCompiler.CompilationResult result = compiler.compile(lessSource, configuration);
cssContent = result.getCss();
```

1st case: Stylesheet beginning with charset:

``` CSS
@charset "utf-8";

html,body {
    height: 100%;
}
```

Leads to 

```
Caused by: com.github.sommeri.less4j.Less4jException: Could not compile less. 2 error(s) occurred:
ERROR file:/somepath/style.less 1:1 required (...)+ loop did not match anything at input '﻿' in selectors (which started at 1:1)
ERROR file:/somepath/style.less 1:1 no viable alternative at input '﻿' in ruleset (which started at 1:1)
```

How am I supposed to provide a charset for the stylesheet?

2nd case: Stylesheet starting with a variable:

``` CSS
@backgroundColor: rgb(255, 255, 255);

body {
    background-color: @backgroundColor;
}
```

Leads to the same error message(s).

3rd case: Variable declaration after some rule:

``` CSS
body {
    background-color: @backgroundColor;
}

@backgroundColor: rgb(255, 255, 255);
```

Finally works!

As I am new to less4j, the error message was not really helpful but after some tinkering I found out what's going on.
