### ISSUE TITLE
ability to use "externally defined" variables in @import statements

### ISSUE THREAD

**Issue by SomMeri** [SomMeri/less4j#241]
https://github.com/less/less.js/issues/1359

**Comment by Deraen** [comment]
Is this same case:

``` less
@web-font-path: "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700";

.web-font(@path) {
  @import url("@{path}");
}
.web-font(@web-font-path);
```

I'm hitting this problem with the latest Bootswatch version: https://github.com/thomaspark/bootswatch/blob/gh-pages/yeti/bootswatch.less#L5-L10
