### ISSUE TITLE
multiply with alpha didn't work

### ISSUE THREAD

**Issue by NF13** [SomMeri/less4j#293]
```css
.test1 {color:multiply(fade(#A21619, 20%), #ffffff);}
```
excepected value:

```css
.test1 {
  color: #ecd0d1;
}
```

Tested with: http://lesstester.com/

value from less4j:

```css
.test1 {
  color: #a21619;
}
```
