### ISSUE TITLE
Compile with javascript mixin

### ISSUE THREAD

**Issue by danjee** [SomMeri/less4j#300]
I'm having difficulties compiling a mixin that contains some javascript function. Compiling it from brackets was successful.

```less
/*
 * Scale 3d
 */
.scale3d(...) {
  @process: ~`(function(e){return e=e||"1, 1, 1"})((function(){var e="@{arguments}";return e=e.replace(/^\[|\]$/g,"")})())`;
  -webkit-transform: scale3d(@process);
  -moz-transform: scale3d(@process);
  -ms-transform: scale3d(@process);
  -o-transform: scale3d(@process);
  transform: scale3d(@process);
}

// pentru testare
.btn-test{
    background-color: aqua;
    .scale3d(0,0,0);
}
```

The java class that I use is something like this:

```java
public class Test {
	public static void main(String[] args) {
		ThreadUnsafeLessCompiler compiler = new ThreadUnsafeLessCompiler();
		try {
			LessCompiler.Configuration configuration = new LessCompiler.Configuration();
			String source = getLessSource();
			LessCompiler.CompilationResult result = compiler.compile(source, configuration);
			List<LessCompiler.Problem> warnings = result.getWarnings();

			for (LessCompiler.Problem warning : warnings) {
				System.err.println(warning.getMessage());
			}

			String cssContent = result.getCss();
			System.out.println(cssContent);
		} catch (Less4jException x) {
			x.printStackTrace();
		}
	}

	private static String getLessSource() {
		return getStringFromInputStream(Test.class.getResourceAsStream("test.less"));
	}

	private static String getStringFromInputStream(InputStream is) {

		BufferedReader br = null;
		StringBuilder sb = new StringBuilder();

		String line;
		try {

			br = new BufferedReader(new InputStreamReader(is));
			while ((line = br.readLine()) != null) {
				sb.append(line);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (br != null) {
				try {
					br.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}

		return sb.toString();

	}
}
```
This can be fixed ? 
Thank you
