### ISSUE TITLE
Problem with nested mixins

### ISSUE THREAD

**Issue by casph** [SomMeri/less4j#303]
Hi, i've this little problem, above code compile correctly in less, but in less4j throw an exception:
I really cannot understand where is the problem...

```less
.test-case {

  @unit: 5%;

  .test-fn(@n, @important) {
  
      @width: round(@unit * @n, 2);
  
      & when (@important = false) {
        width: @width;
      }
      & when (@important = true) {
        width: @width !important;
      }
  }
  .test-rule(@n, @important: true) {
    .rule-@{n} {
      .test-fn(@n, @important);
    }
  }

  .test-rule(1);
  .test-rule(2, false);
}
```
```
com.github.sommeri.less4j.Less4jException: Could not compile less. 7 error(s) occurred:
no viable alternative at input '(' in ruleset (which started at 539:1)
 550:   .test-fn(@n, @important) {
 551:   
no viable alternative at input '      ' in abstract mixin or namespace (which started at 550:3)
 552:       & when (@important = false) {
 553:         width: round(@unit * @n, 2);
```

Thanks in advance.
