### ISSUE TITLE
Nested import malfunction

### ISSUE THREAD

**Issue by SomMeri** [SomMeri/less4j#308]
File:
````less
@import "import/chained-import-1.less"; //try also with reference
div {
  .mixin();
}
````

`import/chained-import-1.less`:
````less
.mixin {
	aa:aa;
	//@import "chained-import-2.less";
	@import (reference) "chained-import-2.less";
}
````

`import/chained-import-2.less`:
````less
.chained-import-2 {
  content: ~"chained-import-2";
}

````

compiles into:
````css
.mixin {
  aa: aa;
}
div {
  aa: aa;
  @import "chained-import-2.less";
}
````

which is wrong. The `@import "chained-import-2.less";` should not be in the output. It works wrong, but differently wrong, with `reference` being turned on/off.
