### ISSUE TITLE
Allow space around selector attribute operator

### ISSUE THREAD

**Issue by SomMeri** [SomMeri/less4j#313]
Following should compile:
````less
html[a = "ie"] {
    property: value;
}
````

Caused issue number 1 in #309
