### ISSUE TITLE
Do not support the function

### ISSUE THREAD

**Issue by majianxiong** [SomMeri/less4j#332]
*.less 
![image](https://cloud.githubusercontent.com/assets/887531/13104708/b310f16c-d599-11e5-893b-293d5e7eb174.png)

Error ： 
![image](https://cloud.githubusercontent.com/assets/887531/13104635/3bbde55c-d599-11e5-98c3-2a899caf9b69.png)

**Comment by SomMeri** [comment]
Add `(css)` into import, like this:

````less
@web-font-path: "https://fonts.googleapis.com/css?family=Source+Sans+pro:300,400,700";

.web-font(@path) {
  @import (css) url("@{path}");
}

.web-font(@web-font-path);
````

Explanations: when there is no file suffix, less import assumes that you are trying to import less file and therefore tries to load it and parse it. You have to add `css` option to override it.

Links:
* [Importing Css vs Importing Less](https://github.com/SomMeri/less4j/wiki/Less-Language-Import#importing-css-vs-importing-less)
* [Import options](https://github.com/SomMeri/less4j/wiki/Less-Language-Import#options)
