### ISSUE TITLE
Mixin guard evaluation inconsistency between Node LESS and LESS4J

### ISSUE THREAD

**Issue by twhoff** [SomMeri/less4j#340]
I'm running into an issue where I can't detect when a value has been set as just 0 (no units). The code I am trying to use looks like this:

```
.test-1 {
    .test(0);
}
.test-2 {
    .test(0em);
}
.test-3 {
    .test(0px);
}
.test(@val) when (@val = ~'0') {
    okay: yes;
}
```

In Node LESS, this compiles to:

```
.test-1 {
  okay: yes;
}
```

However, in LESS4J it doesn't generate any output (i.e. no guard evaluated to true).

**Comment by SomMeri** [comment]
Thank you, it is a bug.

Workaround:

``` less
.test(@val) when ((@val = 0) and (get-unit(@val) = ~"" )) {
    okay: yes get-unit(@val);
}
```
