### ISSUE TITLE
fails to parse ie-related hack using star prefix

### ISSUE THREAD

**Issue by cwhatley** [SomMeri/less4j#46]
Sample LESS file:

``` less
.border-box {
    box-sizing: border-box;
    *behavior: url(/js/polyfill/boxsizing.htc); 
}
```

This is accepted by lessc just fine and the latest less4j I downloaded today won't parse it.

From the author of the polyfill @ https://github.com/Schepp/box-sizing-polyfill

> If you prefix the behavior property with a star, like seen above, 
> it will only be seen by IE6 & IE7, not by IE8+ (it's a hack) which 
> is better for the performance on those newer browsers.

Also note this page for more css selector hacks (yes, this is ugly, but important):

http://centricle.com/ref/css/filters/
